### PR TITLE
chore: v5.3.1

### PR DESCRIPTION
**Pull request by Pytal**
## [v5.3.1](https://github.com/nextcloud-libraries/nextcloud-dialogs/tree/v5.3.1) (2024-04-16)
[Full Changelog](https://github.com/nextcloud-libraries/nextcloud-dialogs/compare/v5.3.0...v5.3.1)

### Fixes
* fix: Close actions after creating directory and enter it automatically [\#1302](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1302) \([susnux](https://github.com/susnux)\)
* fix: Fix incorrect directory contents when navigating quickly [\#1299](https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1299) \([Pytal](https://github.com/Pytal)\)

### Changed
* Dependency updates

### CODE REVIEW

**Review by susnux — APPROVED** [review]
:+1:

**Comment by Pytal** [comment]
Can you recrete the release because @susnux?

Workflows failing due to check-actor-permission :(

**Comment by Pytal** [comment]
Can you recreate the release @susnux?

Workflows failing due to `check-actor-permission` :(

**Comment by susnux** [comment]
we should update the workflow.

**Comment by Pytal** [comment]
Worked thanks!

**Pull request merged**
