### PR TITLE
fix(FilePicker): Allow using on public shares

### PR DESCRIPTION
**Pull request by susnux**
* Resolves https://github.com/nextcloud/server/issues/42009

Only query settings from the files app when we are on the internal view.
Also adjusted the webdav endpoint used when we are on a public share.

### CODE REVIEW

**Review by emoral435 — APPROVED** [review]
Code LGTM! Haven't tested it, though!

**Comment by ShGKme** [comment]
Is there a plan to have a release with this fix?

This allows using the component outside of the server rendered page, for example, in Talk Desktop.

**Comment by susnux** [comment]
This is already released in 5.1.2

**Comment by ShGKme** [comment]
> This is already released in 5.1.2

Thanks! Sorry, I checked only by milestone

**Pull request merged**
