### PR TITLE
fix(FilePicker): Fix selecting rows using the keyboard

### PR DESCRIPTION
**Pull request by susnux**
Selecting by keyboard was broken due to wrong event and key name.

### CODE REVIEW

**Comment by susnux** [comment]
Ref: https://github.com/perry-mitchell/webdav-client/issues/355

**Review by skjnldsv — APPROVED** [review]

**Comment by susnux** [comment]
Not sure what to do here. Merge without tests? Is there some way to ignore the package exports? Last resort: Fork the project as like with vue-select?

**Comment by skjnldsv** [comment]
> Not sure what to do here. Merge without tests? Is there some way to ignore the package exports? Last resort: Fork the project as like with vue-select?

Import with relative path.

**Comment by susnux** [comment]
> Import with relative path.

This might work for apps or server, but not for libraries. You can not know that the package is installed at that location.
So for libraries this only works if we bundle the dependency inside the library.

As all of those are possible:
```
server
  |- node_modules
      |- @nextcloud/dialogs
      |- webdav
```
or
```
server
  |- node_modules
      |- @nextcloud/dialogs
          |- node_modules
              |- webdav
```
or
```
server
  |- node_modules
      |- @nextcloud/dialogs
          |- node_modules
              |- @nextcloud/files
                  |- node_modules
                      |- webdav
```

**Comment by skjnldsv** [comment]
Indeed, I only tried with Apps

**Comment by susnux** [comment]
See #949 for a solution until it is fixed, after that one is merged, this can be rebased and should work :)

**Pull request merged**
