### PR TITLE
v4.2.0-beta.5

### PR DESCRIPTION
**Pull request by Pytal**
### :bug: Fixed bugs
* [stable4] fix(FilePicker): Fix legacy entry point buttons when bundling with webpack by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/945
* [stable4] Make file list only sortable by one property at the time by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/951
* [stable4] Fix FilePicker keyboard handling by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/954
* [stable4] fix: Make eslint happy by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/955
* [stable4] Center heading of dialog by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/967
* [stable4] fix(FilePicker): Only show checkbox skeletons if multiselect was enabled by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/970
* [stable4] Fix styling issues and make the FilePicker height fixed by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/972
* [stable4] fix(FilePicker): Reset selected files if the current directory is change by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/968
* [stable4] fix(l10n): Extract translations also from vue SFC template attributes by @susnux in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/966

### CODE REVIEW

**Comment by Pytal** [comment]
Pending changelog

**Comment by Pytal** [comment]
Changelog generation action used v5.0.0-beta.2 as initial tag 💀

**Comment by Pytal** [comment]
Changelog auto-generated with GitHub

**Review by skjnldsv — APPROVED** [review]

**Comment by Pytal** [comment]
Admin power to be directed 👉 https://github.com/nextcloud-libraries/nextcloud-dialogs/actions/runs/6087895015

**Pull request merged**
